#!/usr/bin/env python3


from datetime import datetime
from subprocess import call
import os
import sys
from sys import exit
import configparser

try:
	import requests
	import pyperclip
except ImportError:
	print("Could not import a required module - are python-requests and pyperlclip installed?")
	exit()

def readConfig():
	path = sys.path[0]
	config = configparser.ConfigParser()
	config.read(path+'/pymfconfig')
	image_dir = config.get('config', 'image_dir')
	image_format = config.get('config', 'image_format')
	date_format = config.get('config', 'date_format')
	return (image_dir, image_format, date_format)

def getImage():
	image_dir, image_format, date_format = readConfig()
	date_stamp = (datetime.now().strftime(date_format)+(image_format))
	file_uri = image_dir+date_stamp 
	call(["maim", "-s", file_uri])

	return (file_uri)


def main():
	

	upload = getImage()

	try:
		response = requests.post(
			url="http://pomf.se/upload.php",
			files={"files[]":open(upload, "rb")}
		)
	except Exception as e:
		print("Error uploading {0}".format(e))
		exit()

	local = upload.split('/')
	local = (local[-1] if len(local) > 1 else local[0])

	remote = "http://a.pomf.se/" + response.text.split('"')[17]

	pyperclip.copy(remote)

#	print(local + " -> " + remote)
#	print("copied to clipboard maybe??")

if __name__ == '__main__':
	main()
